server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/corefitpro?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: developer
    password: 1234567
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      generate_statistics: true
    show-sql: false
    open-in-view: false