server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/corefitpro?currentSchema=public
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      generate_statistics: true
    show-sql: false
    open-in-view: false