CREATE TABLE physical_assessments (
    id                    UUID             NOT NULL DEFAULT gen_random_uuid(),
    trainee_id            UUID             NOT NULL,
    registered_at         DATE             NOT NULL,
    age                   INT              NULL,
    weight                DOUBLE PRECISION NULL,
    height                DOUBLE PRECISION NULL,
    imc                   DOUBLE PRECISION NULL,
    body_fat              DOUBLE PRECISION NULL,
    fat_mass              DOUBLE PRECISION NULL,
    muscle_mass           DOUBLE PRECISION NULL,
    chest                 DOUBLE PRECISION NULL,
    waist                 DOUBLE PRECISION NULL,
    abdomen               DOUBLE PRECISION NULL,
    hip                   DOUBLE PRECISION NULL,
    right_arm             DOUBLE PRECISION NULL,
    left_arm              DOUBLE PRECISION NULL,
    right_thigh           DOUBLE PRECISION NULL,
    left_thigh            DOUBLE PRECISION NULL,
    activity_level        VARCHAR(20)      NULL,
    notes                 VARCHAR(500)     NULL,
    front_view_photo_url  VARCHAR(255)     NULL,
    back_view_photo_url   VARCHAR(255)     NULL,
    left_view_photo_url   VARCHAR(255)     NULL,
    right_view_photo_url  VARCHAR(255)     NULL,
    CONSTRAINT pk_physical_assessments PRIMARY KEY (id),
    CONSTRAINT fk_physical_assessments_trainee FOREIGN KEY (trainee_id) REFERENCES trainees (id) ON DELETE CASCADE
);
